apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-web-app
  name: flask-web-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web-app
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-web-app
        flask: "true"
    spec:
      containers:
      - image: nvrbckdown/flask-app
        name: flask-app
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: 10.100.100.0
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: uacademy
              key: city
        - name: MENTOR
          valueFrom:
            secretKeyRef:
              name: mentor
              key: name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-app
spec:
  selector:
    app: flask-web-app
  ports:
  - port: 80
    targetPort: 5000
