apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: nvrbckdown/flask-app
        name: flask-app
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: environment
              key: env
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:  
              name: environment
              key: http_port
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: payme
              key: token
        - name: ADDRESS
          valueFrom: 
            secretKeyRef:
              name: payme
              key: address
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: psql
              key: pg_host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: psql
              key: pg_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql
              key: pg_user   
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql
              key: pg_password                 
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: psql
              key: pg_port
        - name: MY_POD_NAME
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:  
            fieldRef:
              fieldPath: spec.nodeName
