name: ci

on:
  push:
    branches:
      - 'main'
env:
  REPO: nvrbckdown/flask-app
  ENV_TAG: latest

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            $REGISTRY/$REPO:$ENV_TAG
